version: 0.2

env:
  variables:
    key: 'value'

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      -
  pre_build:
    commands:
      - deploy_file_name=CloudFormation-CustomResourceService-NoBuild.zip
  build:
    commands:
      # the only times we want to deploy are when the build is triggered manually (both CODEBUILD_WEBHOOK_HEAD_REF and CODEBUILD_WEBHOOK_EVENT will be empty) or the build is triggered for master and the event is not a pull request event
      - |
        if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/master" ] || [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "" ] ; then
          if [ "$CODEBUILD_WEBHOOK_EVENT" != "PULL_REQUEST_CREATED" ] && [ "$CODEBUILD_WEBHOOK_EVENT" != "PULL_REQUEST_UPDATED" ] && [ "$CODEBUILD_WEBHOOK_EVENT" != "PULL_REQUEST_REOPENED" ] ; then
            deploy_file_name=CloudFormation-CustomResourceService.zip
          fi
        fi

      - echo $deploy_file_name

  post_build:
    commands:
      - if ["$CODEBUILD_BUILD_SUCCEEDING" = "0" ] ; then deploy_file_name=CloudFormation-CustomResourceService-$CODEBUILD_RESOLVED_SOURCE_VERSION.zip ; fi
artifacts:
  files:
    - Pipeline.yaml
    - src/CustomResourceService.yaml
  name: $deploy_file_name
  discard-paths: yes

  secondary-artifacts:
    StartFunction:
      files:
        - src/Start.js
      discard-paths: yes

    CallEndpointFunction:
      files:
        - src/CallEndpoint.js
      discard-paths: yes

    ResponseFunction:
      files:
        - src/Response.js
      discard-paths: yes
